PROGRAM = detect-camera
CXX       = g++
CXXFLAGS  = -g -O0 -std=c++17 -Wall $(shell pkg-config --cflags opencv4) 
CFLAGS=
LDFLAGS= $(shell pkg-config --libs opencv4)

$(PROGRAM):  ../libfacedetection/example/detect-camera.cpp ../libfacedetection/src/facedetectcnn.cpp ../libfacedetection/src/facedetectcnn-model.cpp ../libfacedetection/src/facedetectcnn-data.cpp 
	$(CXX) $(CXXFLAGS) $(CFLAGS) -o $(PROGRAM) $^ $(LDFLAGS) 
	
clean:
	-rm *.gcno *.gcda $(PROGRAM)
